# Default values for the application.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# String to partially override application.fullname template (will maintain the release name).
nameOverride: ""
# String to fully override application.fullname template.
fullnameOverride: ""
# Deploy all the components in specific K8s node(s).
chartNodeSelector: {}

# Component api values.
api:
  tier: external
  replicaCount: 1

  # Configuration of the container image.
  imagePullSecrets: []
  image:
    repository: eclipseaerios/llo-api
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
    pullPolicy: IfNotPresent

  # Configuration of the service
  service:
    type: NodePort
    nodePort: ""

  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi

  autoscaling:
    enabled: false

  podSecurityContext: {}
  securityContext: {}
    
  # Configure this parameters to deploy the component in specific K8s node(s).
  nodeSelector: {}
  tolerations: []
  affinity: {}
